export type ToolField = { key: string; label: string; placeholder?: string; value: string; type?: "textarea" | "number" | "select" | "checkbox"; options?: string[]; min?: number; max?: number };
export type ToolResult = { title: string; metrics: [string, string][]; columns?: string[]; rows?: string[][]; text?: string; color?: string; preview?: { title: string; description: string; domain: string } };
export type Workspace = { inputTitle: string; action: string; fields: ToolField[]; sample: ToolResult; local?: boolean };
const domain: ToolField = { key: "target", label: "Domain", placeholder: "example.com", value: "example.com" };
const ip: ToolField = { key: "target", label: "IP address", placeholder: "8.8.8.8", value: "8.8.8.8" };
const url: ToolField = { key: "target", label: "Website URL", placeholder: "https://example.com", value: "https://example.com" };
const select = (key: string, label: string, options: string[], value = options[0] ?? ""): ToolField => ({ key, label, options, value, type: "select" });
const check = (key: string, label: string): ToolField => ({ key, label, value: "true", type: "checkbox" });

export const workspaces: Record<string, Workspace> = {
  "ip-lookup": { inputTitle: "Locate an address", action: "Preview lookup", fields: [ip], sample: { title: "IP overview", metrics: [["IP address", "8.8.8.8"], ["Organization", "Google LLC"], ["Location", "Mountain View, US"], ["Network", "AS15169"]], columns: ["Property", "Value"], rows: [["Country", "United States"], ["Region", "California"], ["Timezone", "America/Los_Angeles"], ["Address type", "IPv4 · Public"], ["Hostname", "dns.google"]] } },
  "ip-reputation": { inputTitle: "Inspect an IP address", action: "Preview reputation", fields: [ip], sample: { title: "Blocklist report", metrics: [["IP address", "8.8.8.8"], ["Listed", "0 of 4"], ["Risk signal", "Low"], ["Sources", "4 blocklists"]], columns: ["Blocklist", "Status", "Detail"], rows: [["Spamhaus ZEN", "Not listed", "No listing found"], ["SpamCop", "Not listed", "No listing found"], ["Barracuda", "Not listed", "No listing found"], ["SORBS", "Not listed", "No listing found"]] } },
  "vpn-check": { inputTitle: "Check network signals", action: "Preview signals", fields: [ip], sample: { title: "Connection classification", metrics: [["IP address", "8.8.8.8"], ["Connection", "Datacenter"], ["Provider", "Google LLC"], ["Confidence", "High"]], columns: ["Signal", "Detected", "Detail"], rows: [["VPN", "No", "No known VPN signature"], ["Proxy", "No", "No proxy signal"], ["Tor exit node", "No", "Not in exit node list"], ["Hosting", "Yes", "Datacenter network"]] } },
  "subnet-calculator": { local: true, inputTitle: "Define your network", action: "Calculate subnet", fields: [{ key: "target", label: "IPv4 network / CIDR", value: "192.168.1.0/24", placeholder: "192.168.1.0/24" }], sample: { title: "Subnet breakdown", metrics: [], rows: [] } },
  "ping-test": { inputTitle: "Measure connectivity", action: "Preview ping", fields: [{ ...domain, label: "Domain or IP address" }, select("count", "Packet count", ["4", "8", "16"]), select("region", "Test region", ["US East", "Europe", "Asia Pacific"])], sample: { title: "Latency report", metrics: [["Average", "24.8 ms"], ["Minimum", "22.1 ms"], ["Maximum", "27.6 ms"], ["Packet loss", "0%"]], columns: ["Sequence", "Destination", "Latency", "Status"], rows: [["1", "93.184.215.14", "22.1 ms", "Received"], ["2", "93.184.215.14", "24.5 ms", "Received"], ["3", "93.184.215.14", "27.6 ms", "Received"], ["4", "93.184.215.14", "25.0 ms", "Received"]] } },
  "dns-lookup": { inputTitle: "Resolve a domain", action: "Preview records", fields: [domain, select("record", "Record type", ["A", "AAAA", "MX", "TXT", "CNAME", "NS", "SOA", "CAA", "ANY"]), select("resolver", "DNS resolver", ["Cloudflare · 1.1.1.1", "Google · 8.8.8.8", "Quad9 · 9.9.9.9"])], sample: { title: "DNS records", metrics: [["Domain", "example.com"], ["Record type", "A"], ["Records", "2"], ["Query time", "18 ms"]], columns: ["Name", "Type", "TTL", "Value"], rows: [["example.com", "A", "300", "93.184.215.14"], ["example.com", "A", "300", "93.184.215.15"]] } },
  "dns-propagation": { inputTitle: "Compare global resolvers", action: "Preview propagation", fields: [domain, select("record", "Record type", ["A", "AAAA", "CNAME", "MX", "TXT", "NS"])], sample: { title: "Global DNS snapshot", metrics: [["Domain", "example.com"], ["Agreement", "5 of 6"], ["Record type", "A"], ["Resolvers", "6 locations"]], columns: ["Location", "Resolver", "Answer", "Status"], rows: [["United States", "Google", "93.184.215.14", "Matches"], ["Germany", "Cloudflare", "93.184.215.14", "Matches"], ["Singapore", "Quad9", "93.184.215.14", "Matches"], ["Japan", "Google", "93.184.215.14", "Matches"], ["Australia", "Cloudflare", "93.184.215.14", "Matches"], ["Brazil", "Quad9", "93.184.215.15", "Different"]] } },
  "is-it-down": { inputTitle: "Check a website", action: "Preview availability", fields: [url, select("region", "Test region", ["US East", "Europe", "Asia Pacific"])], sample: { title: "Availability report", metrics: [["Website", "example.com"], ["HTTP status", "200 OK"], ["Response time", "142 ms"], ["Availability", "Reachable"]], columns: ["Check", "Result"], rows: [["DNS resolution", "Resolved"], ["TLS connection", "Established"], ["HTTP response", "200 OK"], ["Redirects", "0"]] } },
  "bulk-url-status": { inputTitle: "Check multiple websites", action: "Preview URL report", fields: [{ key: "target", label: "URLs · one per line", type: "textarea", value: "https://example.com\nhttps://example.org\nhttps://example.net", placeholder: "https://example.com\nhttps://example.org" }], sample: { title: "URL status report", metrics: [["URLs", "3"], ["Reachable", "2"], ["Redirected", "1"], ["Errors", "0"]], columns: ["URL", "Status", "Time", "Final destination"], rows: [["https://example.com", "200 OK", "142 ms", "https://example.com"], ["https://example.org", "200 OK", "168 ms", "https://example.org"], ["https://example.net", "301 Redirect", "96 ms", "https://www.example.net"]] } },
  "http-headers": { inputTitle: "Inspect a response", action: "Preview headers", fields: [url, select("method", "HTTP method", ["HEAD", "GET"]), check("redirects", "Follow redirects")], sample: { title: "Response headers", metrics: [["Status", "200 OK"], ["Protocol", "HTTP/2"], ["Time", "142 ms"], ["Headers", "5"]], columns: ["Header", "Value"], rows: [["content-type", "text/html; charset=UTF-8"], ["cache-control", "max-age=3600"], ["server", "nginx"], ["content-encoding", "gzip"], ["strict-transport-security", "max-age=31536000; includeSubDomains"]] } },
  "security-headers": { inputTitle: "Inspect website protection", action: "Preview security report", fields: [url], sample: { title: "Security header audit", metrics: [["Grade", "B"], ["Present", "4 of 6"], ["Missing", "2"], ["Website", "example.com"]], columns: ["Header", "Status", "Value / recommendation"], rows: [["Strict-Transport-Security", "Present", "max-age=31536000"], ["Content-Security-Policy", "Missing", "Define a policy for allowed content sources"], ["X-Content-Type-Options", "Present", "nosniff"], ["X-Frame-Options", "Present", "DENY"], ["Referrer-Policy", "Present", "strict-origin-when-cross-origin"], ["Permissions-Policy", "Missing", "Restrict unused browser features"]] } },
  "email-deliverability": { inputTitle: "Inspect email authentication", action: "Preview email report", fields: [domain, { key: "selector", label: "DKIM selector", value: "default", placeholder: "default" }], sample: { title: "Email authentication", metrics: [["Domain", "example.com"], ["SPF", "Valid"], ["DKIM", "Found"], ["DMARC", "Monitoring"]], columns: ["Record", "Status", "Value"], rows: [["SPF", "Valid", "v=spf1 include:_spf.example.com ~all"], ["DKIM · default", "Found", "v=DKIM1; k=rsa; p=…"], ["DMARC", "Monitoring", "v=DMARC1; p=none; rua=mailto:dmarc@example.com"], ["MX", "Found", "10 mail.example.com"]] } },
  "ssl-certificate": { inputTitle: "Inspect a certificate", action: "Preview certificate", fields: [domain, { key: "port", label: "Port", type: "number", value: "443", min: 1, max: 65535 }], sample: { title: "Certificate details", metrics: [["Hostname", "example.com"], ["Trust", "Valid chain"], ["Issuer", "Example Certificate Authority"], ["Protocol", "TLS 1.3"]], columns: ["Property", "Value"], rows: [["Subject", "CN=example.com"], ["Valid from", "2026-10-01"], ["Expires", "2026-12-30"], ["Signature", "SHA256 with RSA"], ["Alternative names", "example.com, www.example.com"]] } },
  "seo-checker": { inputTitle: "Inspect page metadata", action: "Preview SEO audit", fields: [url], sample: { title: "On-page SEO audit", metrics: [["Score", "86 / 100"], ["Passed", "5 checks"], ["Warnings", "1"], ["Indexing", "Allowed"]], columns: ["Check", "Status", "Detail"], rows: [["Page title", "Passed", "Example Domain · 14 characters"], ["Meta description", "Warning", "Add a descriptive summary of this page"], ["Canonical URL", "Passed", "https://example.com/"], ["H1 heading", "Passed", "Example Domain"], ["Robots", "Passed", "index, follow"], ["Image alt text", "Passed", "All images have alternative text"]] } },
  "open-graph-preview": { inputTitle: "Inspect social metadata", action: "Preview social card", fields: [url, select("platform", "Platform", ["Open Graph", "X / Twitter", "LinkedIn"])], sample: { title: "Social sharing preview", metrics: [["Type", "website"], ["Title", "Example Domain"], ["Image", "Not provided"], ["URL", "example.com"]], preview: { title: "Example Domain", description: "A sample page for documentation and illustrative examples.", domain: "example.com" }, columns: ["Tag", "Value"], rows: [["og:title", "Example Domain"], ["og:description", "A sample page for documentation and illustrative examples."], ["og:url", "https://example.com/"], ["og:type", "website"], ["og:image", "Not provided"]] } },
  "password-generator": { local: true, inputTitle: "Choose password settings", action: "Generate password", fields: [{ key: "length", label: "Password length", type: "number", value: "24", min: 8, max: 128 }, check("upper", "Uppercase (A–Z)"), check("lower", "Lowercase (a–z)"), check("digits", "Numbers (0–9)"), check("symbols", "Symbols (!@#$)")], sample: { title: "Generated password", metrics: [], text: "" } },
  "random-color": { local: true, inputTitle: "Choose color output", action: "Generate color", fields: [select("format", "Color format", ["HEX", "RGB", "HSL"])], sample: { title: "Your color", metrics: [], text: "" } },
  "word-counter": { local: true, inputTitle: "Your text", action: "Count text", fields: [{ key: "target", label: "Text", type: "textarea", value: "", placeholder: "Paste or write your text here…" }], sample: { title: "Text statistics", metrics: [] } },
  "smart-dispatcher": { local: true, inputTitle: "Identify a target", action: "Identify target", fields: [{ ...domain, label: "URL, domain, or IP address", placeholder: "https://example.com or 8.8.8.8" }], sample: { title: "Target classification", metrics: [] } },
  "traceroute": { inputTitle: "Trace a network path", action: "Preview route", fields: [{ ...domain, label: "Domain or IP address" }, select("hops", "Maximum hops", ["15", "30", "64"], "30"), select("region", "Test region", ["US East", "Europe", "Asia Pacific"])], sample: { title: "Network hops", metrics: [["Destination", "example.com"], ["Hops", "5"], ["Final latency", "24.8 ms"], ["Path", "Complete"]], columns: ["Hop", "IP address", "Hostname", "Latency"], rows: [["1", "192.168.1.1", "gateway.local", "1.2 ms"], ["2", "10.0.0.1", "isp-edge", "4.6 ms"], ["3", "203.0.113.1", "transit-router", "12.3 ms"], ["4", "203.0.113.2", "destination-edge", "21.1 ms"], ["5", "93.184.215.14", "example.com", "24.8 ms"]] } },
  "port-check": { inputTitle: "Inspect a service port", action: "Preview port check", fields: [{ ...domain, label: "Domain or IP address" }, { key: "port", label: "Port", value: "443", type: "number", min: 1, max: 65535 }, select("protocol", "Protocol", ["TCP", "UDP"])], sample: { title: "Service availability", metrics: [["Host", "example.com"], ["Port", "443"], ["Protocol", "TCP"], ["Status", "Open"]], columns: ["Property", "Result"], rows: [["Service", "HTTPS"], ["Connection", "Accepted"], ["Response time", "28 ms"], ["Resolved address", "93.184.215.14"]] } },
};

export function defaultValues(workspace: Workspace) {
  return Object.fromEntries(workspace.fields.map(field => [field.key, field.value]));
}

export function validateTarget(slug: string, values: Record<string, string>) {
  const target = values["target"]?.trim() ?? "";
  if (["password-generator", "random-color", "word-counter"].includes(slug)) return "";
  if (slug === "subnet-calculator") return /^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/.test(target) && target.split("/")[0]?.split(".").every(n => Number(n) <= 255) && Number(target.split("/")[1]) <= 32 ? "" : "Enter an IPv4 network with a prefix from /0 to /32.";
  const validIp = (value: string) => /^\d{1,3}(\.\d{1,3}){3}$/.test(value) ? value.split(".").every(n => Number(n) <= 255) : (() => { try { return value.includes(":") && new URL(`http://[${value}]/`).hostname.length > 0; } catch { return false; } })();
  const validHost = (value: string) => validIp(value) || (value.length <= 253 && value.includes(".") && value.split(".").every(part => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(part)));
  const validUrl = (value: string) => { try { const parsed = new URL(value); return ["http:", "https:"].includes(parsed.protocol) && validHost(parsed.hostname.replace(/^\[|\]$/g, "")); } catch { return false; } };
  if (["ip-lookup", "ip-reputation", "vpn-check"].includes(slug)) return validIp(target) ? "" : "Enter a valid IPv4 or IPv6 address.";
  if (slug === "bulk-url-status") { const urls = target.split(/\n/).map(line => line.trim()).filter(Boolean); return urls.length > 0 && urls.length <= 50 && urls.every(validUrl) ? "" : "Enter up to 50 valid HTTP or HTTPS URLs, one per line."; }
  if (["is-it-down", "http-headers", "security-headers", "seo-checker", "open-graph-preview"].includes(slug)) return validUrl(target) ? "" : "Enter a full HTTP or HTTPS URL.";
  return validHost(target) || (slug === "smart-dispatcher" && validUrl(target)) ? "" : "Enter a valid domain or IP address.";
}