export type ToolField = { key: string; label: string; placeholder?: string; value: string; type?: "textarea" | "number" | "select" | "checkbox"; options?: string[]; min?: number; max?: number };
export type ToolResult = { title: string; metrics: [string, string][]; columns?: string[]; rows?: string[][]; text?: string; color?: string; preview?: { title: string; description: string; domain: string }; live?: boolean };
export type Workspace = { inputTitle: string; action: string; fields: ToolField[]; sample: ToolResult; local?: boolean; live?: boolean; command?: CommandTemplate };
export type CommandTemplate = { windows: string; linux: string; darwin: string; sampleOutput: string };
const domain: ToolField = { key: "target", label: "Domain", placeholder: "example.com", value: "example.com" };
const ip: ToolField = { key: "target", label: "IP address", placeholder: "8.8.8.8", value: "8.8.8.8" };
const url: ToolField = { key: "target", label: "Website URL", placeholder: "https://example.com", value: "https://example.com" };
const select = (key: string, label: string, options: string[], value = options[0] ?? ""): ToolField => ({ key, label, options, value, type: "select" });
const check = (key: string, label: string): ToolField => ({ key, label, value: "true", type: "checkbox" });

export const workspaces: Record<string, Workspace> = {
  "ip-lookup": { live: true, inputTitle: "Locate an address", action: "Look up IP", fields: [ip], sample: { title: "IP overview", metrics: [["IP address", "8.8.8.8"], ["Organization", "Google LLC"], ["Location", "Mountain View, US"], ["Network", "AS15169"]], columns: ["Property", "Value"], rows: [["Country", "United States"], ["Region", "California"], ["Timezone", "America/Los_Angeles"], ["Address type", "IPv4 · Public"], ["Hostname", "dns.google"]] } },
  "ip-reputation": { live: true, inputTitle: "Inspect an IP address", action: "Check reputation", fields: [ip], sample: { title: "Blocklist report", metrics: [["IP address", "8.8.8.8"], ["Listed", "0 of 4"], ["Risk signal", "Low"], ["Sources", "4 blocklists"]], columns: ["Blocklist", "Status", "Detail"], rows: [["Spamhaus ZEN", "Not listed", "No listing found"], ["SpamCop", "Not listed", "No listing found"], ["Barracuda", "Not listed", "No listing found"], ["SORBS", "Not listed", "No listing found"]] } },
  "vpn-check": { live: true, inputTitle: "Check network signals", action: "Inspect IP", fields: [ip], sample: { title: "Connection classification", metrics: [["IP address", "8.8.8.8"], ["Connection", "Datacenter"], ["Provider", "Google LLC"], ["Confidence", "High"]], columns: ["Signal", "Detected", "Detail"], rows: [["VPN", "No", "No known VPN signature"], ["Proxy", "No", "No proxy signal"], ["Tor exit node", "No", "Not in exit node list"], ["Hosting", "Yes", "Datacenter network"]] } },
  "subnet-calculator": { local: true, inputTitle: "Define your network", action: "Calculate subnet", fields: [{ key: "target", label: "IPv4 network / CIDR", value: "192.168.1.0/24", placeholder: "192.168.1.0/24" }], sample: { title: "Subnet breakdown", metrics: [], rows: [] } },
  "dns-lookup": { live: true, inputTitle: "Resolve a domain", action: "Resolve", fields: [domain, select("record", "Record type", ["A", "AAAA", "MX", "TXT", "CNAME", "NS", "SOA", "CAA", "ANY"])], sample: { title: "DNS records", metrics: [["Domain", "example.com"], ["Record type", "A"], ["Records", "2"], ["Query time", "18 ms"]], columns: ["Name", "Type", "TTL", "Value"], rows: [["example.com", "A", "300", "93.184.215.14"], ["example.com", "A", "300", "93.184.215.15"]] } },
  "dns-propagation": { live: true, inputTitle: "Compare global resolvers", action: "Check propagation", fields: [domain, select("record", "Record type", ["A", "AAAA", "CNAME", "MX", "TXT", "NS"])], sample: { title: "Global DNS snapshot", metrics: [["Domain", "example.com"], ["Agreement", "5 of 6"], ["Record type", "A"], ["Resolvers", "6 locations"]], columns: ["Location", "Resolver", "Answer", "Status"], rows: [["United States", "Google", "93.184.215.14", "Matches"], ["Germany", "Cloudflare", "93.184.215.14", "Matches"], ["Singapore", "Quad9", "93.184.215.14", "Matches"], ["Japan", "Google", "93.184.215.14", "Matches"], ["Australia", "Cloudflare", "93.184.215.14", "Matches"], ["Brazil", "Quad9", "93.184.215.15", "Different"]] } },
  "is-it-down": { live: true, inputTitle: "Check a website", action: "Check availability", fields: [url], sample: { title: "Availability report", metrics: [["Website", "example.com"], ["HTTP status", "200 OK"], ["Response time", "142 ms"], ["Availability", "Reachable"]], columns: ["Check", "Result"], rows: [["DNS resolution", "Resolved"], ["TLS connection", "Established"], ["HTTP response", "200 OK"], ["Redirects", "0"]] } },
  "bulk-url-status": { live: true, inputTitle: "Check multiple websites", action: "Check URLs", fields: [{ key: "target", label: "URLs · one per line", type: "textarea", value: "https://example.com\nhttps://example.org\nhttps://example.net", placeholder: "https://example.com\nhttps://example.org" }], sample: { title: "URL status report", metrics: [["URLs", "3"], ["Reachable", "2"], ["Redirected", "1"], ["Errors", "0"]], columns: ["URL", "Status", "Time", "Final destination"], rows: [["https://example.com", "200 OK", "142 ms", "https://example.com"], ["https://example.org", "200 OK", "168 ms", "https://example.org"], ["https://example.net", "301 Redirect", "96 ms", "https://www.example.net"]] } },
  "http-headers": { live: true, inputTitle: "Inspect a response", action: "Fetch headers", fields: [url, select("method", "HTTP method", ["HEAD", "GET"])], sample: { title: "Response headers", metrics: [["Status", "200 OK"], ["Protocol", "HTTP/2"], ["Time", "142 ms"], ["Headers", "5"]], columns: ["Header", "Value"], rows: [["content-type", "text/html; charset=UTF-8"], ["cache-control", "max-age=3600"], ["server", "nginx"], ["content-encoding", "gzip"], ["strict-transport-security", "max-age=31536000; includeSubDomains"]] } },
  "security-headers": { live: true, inputTitle: "Inspect website protection", action: "Audit security", fields: [url], sample: { title: "Security header audit", metrics: [["Grade", "B"], ["Present", "4 of 6"], ["Missing", "2"], ["Website", "example.com"]], columns: ["Header", "Status", "Value / recommendation"], rows: [["Strict-Transport-Security", "Present", "max-age=31536000"], ["Content-Security-Policy", "Missing", "Define a policy for allowed content sources"], ["X-Content-Type-Options", "Present", "nosniff"], ["X-Frame-Options", "Present", "DENY"], ["Referrer-Policy", "Present", "strict-origin-when-cross-origin"], ["Permissions-Policy", "Missing", "Restrict unused browser features"]] } },
  "email-deliverability": { live: true, inputTitle: "Inspect email authentication", action: "Check email", fields: [domain, { key: "selector", label: "DKIM selector", value: "default", placeholder: "default" }], sample: { title: "Email authentication", metrics: [["Domain", "example.com"], ["SPF", "Valid"], ["DKIM", "Found"], ["DMARC", "Monitoring"]], columns: ["Record", "Status", "Value"], rows: [["SPF", "Valid", "v=spf1 include:_spf.example.com ~all"], ["DKIM · default", "Found", "v=DKIM1; k=rsa; p=…"], ["DMARC", "Monitoring", "v=DMARC1; p=none; rua=mailto:dmarc@example.com"], ["MX", "Found", "10 mail.example.com"]] } },
  "seo-checker": { live: true, inputTitle: "Inspect page metadata", action: "Audit SEO", fields: [url], sample: { title: "On-page SEO audit", metrics: [["Score", "86 / 100"], ["Passed", "5 checks"], ["Warnings", "1"], ["Indexing", "Allowed"]], columns: ["Check", "Status", "Detail"], rows: [["Page title", "Passed", "Example Domain · 14 characters"], ["Meta description", "Warning", "Add a descriptive summary of this page"], ["Canonical URL", "Passed", "https://example.com/"], ["H1 heading", "Passed", "Example Domain"], ["Robots", "Passed", "index, follow"], ["Image alt text", "Passed", "All images have alternative text"]] } },
  "open-graph-preview": { live: true, inputTitle: "Inspect social metadata", action: "Preview social", fields: [url, select("platform", "Platform", ["Open Graph", "X / Twitter", "LinkedIn"])], sample: { title: "Social sharing preview", metrics: [["Type", "website"], ["Title", "Example Domain"], ["Image", "Not provided"], ["URL", "example.com"]], preview: { title: "Example Domain", description: "A sample page for documentation and illustrative examples.", domain: "example.com" }, columns: ["Tag", "Value"], rows: [["og:title", "Example Domain"], ["og:description", "A sample page for documentation and illustrative examples."], ["og:url", "https://example.com/"], ["og:type", "website"], ["og:image", "Not provided"]] } },
  "password-generator": { local: true, inputTitle: "Choose password settings", action: "Generate password", fields: [{ key: "length", label: "Password length", type: "number", value: "24", min: 8, max: 128 }, check("upper", "Uppercase (A–Z)"), check("lower", "Lowercase (a–z)"), check("digits", "Numbers (0–9)"), check("symbols", "Symbols (!@#$)")], sample: { title: "Generated password", metrics: [], text: "" } },
  "random-color": { local: true, inputTitle: "Choose color output", action: "Generate color", fields: [select("format", "Color format", ["HEX", "RGB", "HSL"])], sample: { title: "Your color", metrics: [], text: "" } },
  "word-counter": { local: true, inputTitle: "Your text", action: "Count text", fields: [{ key: "target", label: "Text", type: "textarea", value: "", placeholder: "Paste or write your text here…" }], sample: { title: "Text statistics", metrics: [] } },
  "smart-dispatcher": { local: true, inputTitle: "Identify a target", action: "Identify target", fields: [{ ...domain, label: "URL, domain, or IP address", placeholder: "https://example.com or 8.8.8.8" }], sample: { title: "Target classification", metrics: [] } },
  "what-is-my-ip": { live: true, inputTitle: "Detecting your network", action: "Detect my IP", fields: [], sample: { title: "Your network", metrics: [] } },
  "whois-lookup": { live: true, inputTitle: "Look up a domain's registration", action: "Look up WHOIS", fields: [domain], sample: { title: "Domain registration", metrics: [["Domain", "example.com"], ["Registered", "1995-08-14"], ["Last updated", "2024-08-09"], ["Status", "client transfer prohibited"]], columns: ["Field", "Value"], rows: [["Registrar", "Reserved by IANA · Example domain"], ["Registrant organization", "Internet Assigned Numbers Authority"], ["Creation date", "1995-08-14"], ["Updated date", "2024-08-09"], ["Expiration date", "2025-08-13"], ["Nameservers", "a.iana-servers.net · b.iana-servers.net"], ["DNSSEC", "signedDelegation"], ["Source", "RDAP · live"], ["Cached", "Not stored"]] } },
  "http-latency": { live: true, inputTitle: "Time a real request", action: "Measure latency", fields: [url], sample: { title: "Latency breakdown", metrics: [["URL", "https://example.com"], ["Status", "200 OK"], ["Total time", "168 ms"], ["Slowest phase", "TTFB (92 ms)"]], columns: ["Phase", "Time", "Note"], rows: [["DNS lookup", "14 ms", "Resolved example.com"], ["TCP connect", "28 ms", "TLS handshake started"], ["TLS handshake", "24 ms", "Established in 3 round trips"], ["Time to first byte", "92 ms", "Server response"], ["Content download", "10 ms", "HTML received"], ["Total", "168 ms", "End-to-end"], ["Source", "Browser Performance API · live"]] } },
  "jwt-decoder": { local: true, inputTitle: "Paste a JWT", action: "Decode token", fields: [{ key: "target", label: "JSON Web Token", type: "textarea", value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzA1MzEwOTAwLCJleHAiOjE3MDUzMTQ1MDAsImlzcyI6ImFwcC5leGFtcGxlLmNvbSIsImF1ZCI6InVzZXJzIn0.4f7G8r3xK2vN5pQ9aB1cD6eF0hI8jK3lM2nO5pQ7rS", placeholder: "Paste a JWT here (header.payload.signature)" }], sample: { title: "JWT contents", metrics: [] } },
  "email-header-parser": { local: true, inputTitle: "Paste a raw email header", action: "Parse header", fields: [{ key: "target", label: "Email header (raw)", type: "textarea", value: "Delivered-To: alice@example.com\nReceived: from mail.example.com by mx.inbox.com; Mon, 14 Oct 2024 09:32:11 -0700\nReceived: from sender.example.org (sender.example.org [203.0.113.45]) by mail.example.com with ESMTPS id A1B2C3; Mon, 14 Oct 2024 09:32:09 -0700\nAuthentication-Results: mx.inbox.com; dkim=pass header.i=@example.org; spf=pass smtp.mailfrom=bob@example.org; dmarc=pass\nFrom: Bob <bob@example.org>\nTo: Alice <alice@example.com>\nSubject: Quarterly update\nDate: Mon, 14 Oct 2024 09:32:00 -0700\nMessage-ID: <abc123@example.org>", placeholder: "Paste the full email header here (everything above the body)" }], sample: { title: "Email header parsed", metrics: [] } },
};

export function defaultValues(workspace: Workspace) {
  return Object.fromEntries(workspace.fields.map(field => [field.key, field.value]));
}

export function validateTarget(slug: string, values: Record<string, string>) {
  const target = values["target"]?.trim() ?? "";
  if (["password-generator", "random-color", "word-counter", "what-is-my-ip", "jwt-decoder", "email-header-parser"].includes(slug)) return "";
  if (slug === "subnet-calculator") return /^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/.test(target) && target.split("/")[0]?.split(".").every(n => Number(n) <= 255) && Number(target.split("/")[1]) <= 32 ? "" : "Enter an IPv4 network with a prefix from /0 to /32.";
  const validIp = (value: string) => /^\d{1,3}(\.\d{1,3}){3}$/.test(value) ? value.split(".").every(n => Number(n) <= 255) : (() => { try { return value.includes(":") && new URL(`http://[${value}]/`).hostname.length > 0; } catch { return false; } })();
  const validHost = (value: string) => validIp(value) || (value.length <= 253 && value.includes(".") && value.split(".").every(part => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(part)));
  // Accept either an explicit URL (http://example.com or https://...) or a bare host
  // (example.com, sub.example.com). The fetcher adds the https:// prefix if missing.
  const validUrlOrHost = (value: string) => {
    if (validHost(value)) return true;
    try {
      const parsed = new URL(value);
      return ["http:", "https:"].includes(parsed.protocol) && validHost(parsed.hostname.replace(/^\[|\]$/g, ""));
    } catch { return false; }
  };
  if (["ip-lookup", "ip-reputation", "vpn-check"].includes(slug)) return validIp(target) ? "" : "Enter a valid IPv4 or IPv6 address.";
  if (slug === "bulk-url-status") {
    const urls = target.split(/\n/).map(line => line.trim()).filter(Boolean);
    return urls.length > 0 && urls.length <= 50 && urls.every(validUrlOrHost) ? "" : "Enter up to 50 hosts or URLs, one per line.";
  }
  if (slug === "whois-lookup") return validHost(target) ? "" : "Enter a valid domain (no protocol).";
  if (["is-it-down", "http-headers", "security-headers", "seo-checker", "open-graph-preview", "http-latency"].includes(slug)) return validUrlOrHost(target) ? "" : "Enter a domain or full URL.";
  return validHost(target) || (slug === "smart-dispatcher" && validUrlOrHost(target)) ? "" : "Enter a valid domain or IP address.";
}