/* ================================================================
 * SiteTrace — report-export.js
 * Phase 4 minimal v1: 3 buttons (Download .md / Copy / Download .pdf)
 * available on every tool page after a result is rendered.
 *
 * Usage:
 *   SitetraceReport.show({
 *     tool: 'IP lookup',
 *     url: '/ip-lookup/',
 *     input: '203.0.113.42',
 *     rows: [ { label: 'Country', value: 'United States' }, ... ]
 *   });
 *
 *   SitetraceReport.hide();
 *
 * The mount element is <div id="report-export-mount"></div> which the
 * page owner adds near the result section. The library creates the 3
 * buttons inside it.
 *
 * PDF generation is lazy-loaded: jsPDF (~80 KB minified) is fetched
 * from a CDN only when the user clicks "Download .pdf" the first time.
 * ================================================================ */
(function (global) {
  'use strict';

  const MOUNT_ID = 'report-export-mount';
  const PDF_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
  let jsPDFPromise = null;
  let lastReport = null;

  function $(id) { return document.getElementById(id); }
  function escapeMd(s) {
    return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
  }
  function nowIso() { return new Date().toISOString(); }

  function renderMarkdown(report) {
    const r = report;
    const lines = [];
    lines.push(`# ${r.tool} — sitetrace report`);
    lines.push('');
    lines.push(`- **Generated**: ${nowIso()}`);
    lines.push(`- **Tool**: [${r.tool}](https://sitetrace.it.com${r.url})`);
    if (r.input) lines.push(`- **Input**: \`${escapeMd(r.input)}\``);
    lines.push('');
    lines.push('## Result');
    lines.push('');
    if (r.rows && r.rows.length) {
      lines.push('| Field | Value |');
      lines.push('| --- | --- |');
      for (const row of r.rows) {
        lines.push(`| ${escapeMd(row.label)} | ${escapeMd(row.value)} |`);
      }
      lines.push('');
    } else {
      lines.push('_(no data captured)_');
      lines.push('');
    }
    lines.push('---');
    lines.push('');
    lines.push('Generated by [sitetrace.it.com](https://sitetrace.it.com) — free network tools, no signup, no tracking.');
    return lines.join('\n');
  }

  function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  function downloadMarkdown() {
    if (!lastReport) return;
    const md = renderMarkdown(lastReport);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const slug = (lastReport.tool || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const filename = `sitetrace-${slug}-${nowIso().slice(0, 10)}.md`;
    downloadBlob(blob, filename);
  }

  async function copyMarkdown() {
    if (!lastReport) return;
    const md = renderMarkdown(lastReport);
    try {
      await navigator.clipboard.writeText(md);
      flash('Copied as Markdown');
    } catch (e) {
      // Fallback for older browsers
      const ta = document.createElement('textarea');
      ta.value = md;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand('copy');
        flash('Copied as Markdown');
      } catch (e2) {
        flash('Copy failed — use the Download .md button instead');
      }
      document.body.removeChild(ta);
    }
  }

  function loadJsPDF() {
    if (jsPDFPromise) return jsPDFPromise;
    jsPDFPromise = new Promise((resolve, reject) => {
      if (global.jspdf && global.jspdf.jsPDF) { resolve(global.jspdf.jsPDF); return; }
      const s = document.createElement('script');
      s.src = PDF_CDN;
      s.onload = () => resolve(global.jspdf && global.jspdf.jsPDF);
      s.onerror = () => reject(new Error('Failed to load jsPDF'));
      document.head.appendChild(s);
    });
    return jsPDFPromise;
  }

  function buildPdfDoc(jsPDF, report) {
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    const margin = 48;
    let y = margin;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(20, 20, 20);
    doc.text(report.tool || 'SiteTrace report', margin, y);
    y += 26;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(`Generated ${nowIso()} · sitetrace.it.com${report.url || ''}`, margin, y);
    y += 22;

    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, 612 - margin, y);
    y += 16;

    if (report.input) {
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      doc.text('Input', margin, y);
      doc.setFont('courier', 'normal');
      doc.setTextColor(20, 20, 20);
      doc.text(String(report.input).slice(0, 80), margin + 60, y);
      y += 18;
    }

    if (report.rows && report.rows.length) {
      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(20, 20, 20);
      doc.text('Result', margin, y);
      y += 14;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);

      const labelWidth = 130;
      const valueX = margin + labelWidth;
      const lineHeight = 14;
      const maxValueWidth = 612 - margin - valueX;

      for (const row of report.rows) {
        if (y > 720) { doc.addPage(); y = margin; }

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(80, 80, 80);
        const labelLines = doc.splitTextToSize(String(row.label || ''), labelWidth - 8);
        doc.text(labelLines, margin, y);
        const labelLineCount = labelLines.length;

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(20, 20, 20);
        const valueLines = doc.splitTextToSize(String(row.value == null ? '—' : row.value), maxValueWidth);
        doc.text(valueLines, valueX, y);
        const valueLineCount = valueLines.length;

        const usedLines = Math.max(labelLineCount, valueLineCount);
        y += usedLines * lineHeight + 4;
      }
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `sitetrace.it.com — free tools, no signup. Generated by you, ${nowIso().slice(0, 10)}.`,
        margin,
        770
      );
      doc.text(`Page ${i} of ${pageCount}`, 612 - margin - 60, 770);
    }

    return doc;
  }

  async function downloadPdf() {
    if (!lastReport) return;
    flash('Building PDF…');
    try {
      const jsPDF = await loadJsPDF();
      const doc = buildPdfDoc(jsPDF, lastReport);
      const slug = (lastReport.tool || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-');
      doc.save(`sitetrace-${slug}-${nowIso().slice(0, 10)}.pdf`);
    } catch (e) {
      flash('PDF generation failed — try Download .md instead');
      console.error('[sitetrace] PDF error', e);
    }
  }

  function flash(text) {
    const mount = $(MOUNT_ID);
    if (!mount) return;
    let toast = mount.querySelector('.report-toast');
    if (!toast) {
      toast = document.createElement('span');
      toast.className = 'report-toast';
      toast.style.cssText = 'margin-left:0.6rem;font-size:0.75rem;color:#67e8f9;font-family:JetBrains Mono,monospace;letter-spacing:0.04em;';
      mount.appendChild(toast);
    }
    toast.textContent = text;
    clearTimeout(toast._timer);
    toast._timer = setTimeout(() => { toast.textContent = ''; }, 2200);
  }

  function ensureMount() {
    let mount = $(MOUNT_ID);
    if (!mount) return null;
    if (!mount._wired) {
      mount._wire();
      mount._wired = true;
    }
    return mount;
  }

  function showButtons(report) {
    const mount = ensureMount();
    if (!mount) return;
    mount.hidden = false;
    mount.style.display = '';
    lastReport = report;
  }

  function hideButtons() {
    const mount = $(MOUNT_ID);
    if (mount) {
      mount.hidden = true;
      mount.style.display = 'none';
    }
    lastReport = null;
  }

  // Auto-wire: when the page adds an element with data-tool-report,
  // we read its content (JSON) and show the buttons.
  function autoWire() {
    document.querySelectorAll('[data-tool-report]').forEach((el) => {
      try {
        const data = JSON.parse(el.getAttribute('data-tool-report'));
        el._wire = function () {
          el.innerHTML = `
            <div class="report-export-bar" style="display:flex;flex-wrap:wrap;align-items:center;gap:0.5rem;padding:0.75rem 1rem;margin-top:1rem;border:1px dashed rgba(34,211,238,0.25);border-radius:0.6rem;background:rgba(15,23,42,0.4);">
              <span style="font-family:'JetBrains Mono',monospace;font-size:0.7rem;color:#67e8f9;letter-spacing:0.16em;text-transform:uppercase;">// Export</span>
              <button type="button" data-report-action="md" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(34,211,238,0.30);background:rgba(34,211,238,0.10);color:#67e8f9;cursor:pointer;">Download .md</button>
              <button type="button" data-report-action="copy" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(148,163,184,0.20);background:rgba(15,23,42,0.6);color:#cbd5e1;cursor:pointer;">Copy</button>
              <button type="button" data-report-action="pdf" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(148,163,184,0.20);background:rgba(15,23,42,0.6);color:#cbd5e1;cursor:pointer;">Download .pdf</button>
              <span class="report-toast"></span>
            </div>
          `;
          el.addEventListener('click', function (e) {
            const btn = e.target.closest('[data-report-action]');
            if (!btn) return;
            const action = btn.getAttribute('data-report-action');
            if (action === 'md') downloadMarkdown();
            else if (action === 'copy') copyMarkdown();
            else if (action === 'pdf') downloadPdf();
          });
        };
        if (!lastReport) showButtons(data);
      } catch (e) {
        console.error('[sitetrace] report-export: invalid data-tool-report JSON', e);
      }
    });
  }

  // ---- Generic DOM scraper ----
  // Looks for label/value patterns inside <main>:
  //   - <div class="text-slate-500 ...">Label</div><div>Value</div>  (sitetrace tool pattern)
  //   - <dt>Label</dt><dd>Value</dd>
  //   - <th>Label</th><td>Value</td>
  //   - <div data-label="...">Value</div>
  // Skips elements whose value still contains a "—" placeholder or the .ip-placeholder class.
  function scrapeRows(scope) {
    scope = scope || document.querySelector('main') || document.body;
    const rows = [];

    // Pattern 1: sitetrace label-class + sibling value
    const labels = scope.querySelectorAll('.text-slate-500.text-xs, .text-slate-500.text-sm');
    labels.forEach((label) => {
      const txt = (label.textContent || '').trim();
      if (!txt || txt.length > 80) return;
      // Find sibling value — common selectors: next div, next span, sibling .font-medium
      let val = null;
      const parent = label.parentElement;
      if (parent) {
        for (const sibling of parent.children) {
          if (sibling === label) continue;
          const v = (sibling.textContent || '').trim();
          if (!v) continue;
          if (sibling.classList && (sibling.classList.contains('text-slate-500') || sibling.classList.contains('text-slate-400'))) continue;
          if (sibling.classList && sibling.classList.contains('ip-placeholder')) continue;
          if (v === '—' || v === '-') continue;
          val = v;
          break;
        }
      }
      if (val) rows.push({ label: txt, value: val });
    });

    // Pattern 2: definition lists
    scope.querySelectorAll('dt').forEach((dt) => {
      const dd = dt.nextElementSibling;
      if (!dd || dd.tagName !== 'DD') return;
      const label = (dt.textContent || '').trim();
      const value = (dd.textContent || '').trim();
      if (label && value && value !== '—') rows.push({ label, value });
    });

    // Pattern 3: tables
    scope.querySelectorAll('table tr').forEach((tr) => {
      const th = tr.querySelector('th');
      const td = tr.querySelector('td');
      if (th && td) {
        const label = (th.textContent || '').trim();
        const value = (td.textContent || '').trim();
        if (label && value && value !== '—') rows.push({ label, value });
      }
    });

    // Pattern 4: data-label attribute
    scope.querySelectorAll('[data-label]').forEach((el) => {
      const label = el.getAttribute('data-label').trim();
      const value = (el.textContent || '').trim();
      if (label && value && value !== '—') rows.push({ label, value });
    });

    // De-dupe by label (keep first occurrence)
    const seen = new Set();
    return rows.filter((r) => {
      if (seen.has(r.label)) return false;
      seen.add(r.label);
      return true;
    });
  }

  // Read tool metadata from a <meta name="sitetrace-tool"> tag (every tool page has it).
  function readToolMeta() {
    const m = document.querySelector('meta[name="sitetrace-tool"]');
    if (!m) return { tool: document.title, url: location.pathname };
    return {
      tool: m.getAttribute('data-tool-name') || m.getAttribute('content'),
      url: m.getAttribute('data-tool-url') || location.pathname,
    };
  }

  // Generic auto-bind: poll <main> for change, scrape rows when results stabilize.
  function autoBind() {
    const mount = $(MOUNT_ID);
    if (!mount) return;

    // If a tool already provided data-tool-report, use it (preferred path)
    const explicit = mount.getAttribute('data-tool-report');
    if (explicit) {
      try {
        autoWire();
        return;
      } catch (e) {}
    }

    // Otherwise scrape the DOM
    const meta = readToolMeta();
    let lastSnapshot = '';
    let timer = null;

    function tryCapture() {
      const rows = scrapeRows();
      if (rows.length < 2) return false; // ignore empty / partial
      const snap = JSON.stringify(rows);
      if (snap === lastSnapshot) return false;
      lastSnapshot = snap;

      // Capture input from common places
      let input = '';
      const inputEl = document.querySelector('input[type="text"], input[type="url"], input[type="search"], input:not([type])');
      if (inputEl && inputEl.value) input = inputEl.value;
      if (!input) {
        const hashEl = document.querySelector('[data-input], .input-mirror, code');
        if (hashEl) input = (hashEl.textContent || '').trim();
      }

      SitetraceReport.show({
        tool: meta.tool,
        url: meta.url,
        input: input,
        rows: rows,
      });
      return true;
    }

    // Initial wire so buttons appear
    mount._wire = function () {
      mount.innerHTML = `
        <div class="report-export-bar" style="display:flex;flex-wrap:wrap;align-items:center;gap:0.5rem;padding:0.75rem 1rem;margin-top:1.5rem;border:1px dashed rgba(34,211,238,0.25);border-radius:0.6rem;background:rgba(15,23,42,0.4);">
          <span style="font-family:'JetBrains Mono',monospace;font-size:0.7rem;color:#67e8f9;letter-spacing:0.16em;text-transform:uppercase;">// Export</span>
          <button type="button" data-report-action="md" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(34,211,238,0.30);background:rgba(34,211,238,0.10);color:#67e8f9;cursor:pointer;">Download .md</button>
          <button type="button" data-report-action="copy" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(148,163,184,0.20);background:rgba(15,23,42,0.6);color:#cbd5e1;cursor:pointer;">Copy</button>
          <button type="button" data-report-action="pdf" style="font-family:'IBM Plex Sans',sans-serif;font-size:0.78rem;font-weight:600;padding:0.4rem 0.75rem;border-radius:0.4rem;border:1px solid rgba(148,163,184,0.20);background:rgba(15,23,42,0.6);color:#cbd5e1;cursor:pointer;">Download .pdf</button>
          <span class="report-toast"></span>
        </div>
      `;
      mount.addEventListener('click', function (e) {
        const btn = e.target.closest('[data-report-action]');
        if (!btn) return;
        const action = btn.getAttribute('data-report-action');
        if (action === 'md') downloadMarkdown();
        else if (action === 'copy') copyMarkdown();
        else if (action === 'pdf') downloadPdf();
      });
    };

    // Watch DOM for changes; debounce + scrape
    const observer = new MutationObserver(() => {
      clearTimeout(timer);
      timer = setTimeout(() => { tryCapture(); }, 400);
    });
    const main = document.querySelector('main') || document.body;
    observer.observe(main, { childList: true, subtree: true, characterData: true });

    // Initial attempt + every 2s for the first 10s (in case results load async)
    tryCapture();
    let ticks = 0;
    const interval = setInterval(() => {
      if (tryCapture() || ++ticks > 5) clearInterval(interval);
    }, 2000);
  }

  global.SitetraceReport = {
    show: function (data) {
      lastReport = data;
      showButtons(data);
    },
    hide: hideButtons,
    getCurrent: function () { return lastReport; },
    refresh: autoWire,
    scrape: scrapeRows,
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => { autoWire(); autoBind(); });
  } else {
    autoWire();
    autoBind();
  }
})(window);